---
- name: ping
  ping:
- name: 创建存放安装包文件
  shell: mkdir -p /files/nginx #创建nginx包目录

- name: 导入安装包
  copy: src=/package/nginx-1.10.2.tar.gz dest=/files/nginx backup=yes
  register: cp_nginx
- debug: var=cp_nginx

- name: 安装nginx
  script: installnginx.sh
  register: nginx_re
- debug: var=nginx_re

- name: 传 nginx.conf
  template: src=nginxconf.j2 dest=/usr/local/nginx/conf/nginx.conf backup=yes
  register: cp_ngcn
- debug: var=cp_ngcn
- name: 修改host文件
  shell: echo "`hostname -I | awk '{print $1}'` www.wang.com" >> /etc/hosts

- name: 传www.conf
  template: src=www_conf.j2 dest=/usr/local/nginx/conf/extra/www.conf
  notify: reload_nginx
  register: ng_cnf
- debug: var=ng_cnf

- name: 测试端口
  shell: ss -antup |grep nginx
  register: ng_rq
- debug: var=ng_rq
