---
- name: ping服务器
  ping:
- name: 创建存放安装包文件
  shell: mkdir -p /files/mysql #创建mysql包目录
- name: 导入安装包
  copy: src=/package/mysql-5.5.32-linux2.6-x86_64.tar.gz dest=/files/mysql backup=no
  register: cp_mysql
- debug: var=cp_mysql

- name: 安装mysql
  script: installmysql.sh
  register: in_mysql_register
- debug: var=in_mysql_register

- name: 测试端口
  shell: ss -antup |grep mysqld
  register: my_rq
- debug: var=my_rq
