---
- name: start_nginx #定义handlers的动作类型
  shell: /usr/local/nginx/sbin/nginx
- name: stop_nginx #定义handlers的动作类型
  shell: /usr/local/nginx/sbin/nginx -s stop
- name: reload_nginx #定义handlers的动作类型
  shell: /usr/local/nginx/sbin/nginx -s reload
- name: t_nginx
  shell: /usr/local/nginx/sbin/nginx -t
