---
- name: start_php       #定义handlers的动作类型
  shell: /usr/local/php/sbin/php-fpm 
- name: stop_php       #定义handlers的动作类型
  shell: kill -INT `cat /usr/local/php/var/run/php-fpm.pid`  
- name: reload_php    #定义handlers的动作类型
  shell: kill -USR2 `cat /usr/local/php/var/run/php-fpm.pid`

- name: start_nginx #定义handlers的动作类型
  shell: /usr/local/nginx/sbin/nginx
- name: stop_nginx #定义handlers的动作类型
  shell: /usr/local/nginx/sbin/nginx -s stop
- name: reload_nginx #定义handlers的动作类型
  shell: /usr/local/nginx/sbin/nginx -s reload
- name: t_nginx
  shell: /usr/local/nginx/sbin/nginx -t


